name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # v1.0.0 のようなタグでリリース
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
          - os: macos-latest
            platform: macos
            arch: universal
          - os: ubuntu-latest
            platform: linux
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      
    # Linux用の依存関係インストール
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
          
    # Windows: 従来通りnpm使用
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: npm install
      
    # Linux/macOS: npm問題回避でCargo使用
    - name: Install Tauri CLI (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: cargo install tauri-cli
      
    # Windows: npmスクリプト使用
    - name: Build Tauri app (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run build:windows
      
    # Linux/macOS: 手動ビルド
    - name: Prepare and build (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p dist
        cp src-web/main.js dist/bundle.js
        cp src-web/index.html dist/index.html
        cp src-web/styles.css dist/styles.css
        cargo tauri build
      
    # === アーティファクト保存 (開発用) ===
    
    # Windows artifacts
    - name: Upload Windows artifacts
      if: github.ref_type != 'tag' && matrix.platform == 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: atode-windows-${{ matrix.arch }}
        path: src-tauri/target/release/bundle/msi/*.msi
        
    # macOS artifacts  
    - name: Upload macOS artifacts
      if: github.ref_type != 'tag' && matrix.platform == 'macos'
      uses: actions/upload-artifact@v4
      with:
        name: atode-macos-${{ matrix.arch }}
        path: |
          src-tauri/target/release/bundle/macos/*.app
          src-tauri/target/release/bundle/dmg/*.dmg
          
    # Linux artifacts
    - name: Upload Linux artifacts
      if: github.ref_type != 'tag' && matrix.platform == 'linux'
      uses: actions/upload-artifact@v4
      with:
        name: atode-linux-${{ matrix.arch }}
        path: |
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/appimage/*.AppImage
        
    # === リリース作成 (タグ時のみ) ===
    
    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/macos/*.app
          src-tauri/target/release/bundle/dmg/*.dmg
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/appimage/*.AppImage
        generate_release_notes: true
        draft: false
        prerelease: false
        body: |
          ## Atode ${{ github.ref_name }}
          
          ### Downloads
          - **Windows**: Download the `.msi` file
          - **macOS**: Download the `.dmg` file  
          - **Linux**: Download the `.deb` or `.AppImage` file
          
          ### Platform Support
          - ✅ **Windows**: Full feature support including hotkeys
          - ⚠️ **macOS**: Basic features (hotkeys not yet supported)
          - ⚠️ **Linux**: Basic features (hotkeys not yet supported)
          
          ### What's New
          - First stable release with core functionality
          - Cross-platform support (Windows, macOS, Linux)
          - Local SQLite storage
          - Tag-based article organization
          - Site-based filtering
          
          ### Known Limitations
          - Hotkey support is currently Windows-only
          - Browser integration works best on Windows
          
          For issues or feature requests, please visit the [Issues page](https://github.com/frkavka/Atode-GUI/issues).
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
