name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # v1.0.0 のようなタグでリリース
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Clean npm cache and install
      run: |
        npm cache clean --force
        Remove-Item package-lock.json -ErrorAction SilentlyContinue
        npm install
      
    - name: Build Tauri app
      run: npm run build:windows
      
    - name: Upload Windows artifacts (開発用)
      if: github.ref_type != 'tag'
      uses: actions/upload-artifact@v4
      with:
        name: atode-windows-x64
        path: src-tauri/target/release/bundle/msi/*.msi
        
    # タグがpushされた時のみリリース作成
    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v1
      with:
        files: src-tauri/target/release/bundle/msi/*.msi
        generate_release_notes: true
        draft: false
        prerelease: false
        body: |
          ## Atode ${{ github.ref_name }} - Windows Release
          
          ### Download
          - **Windows**: Download the `.msi` file below
          
          ### Features
          - ✅ **Full feature support** including hotkeys (`Ctrl+Shift+S`)
          - ✅ **System tray integration** (`Ctrl+Shift+A`)
          - ✅ **Local SQLite storage** - your data stays private
          - ✅ **Tag-based organization** - organize with custom tags
          - ✅ **Site-based filtering** - find articles by site
          - ✅ **Cross-browser support** - works with Chrome, Edge, Firefox, etc.
          
          ### What's New in v1.0
          - First stable release
          - Core functionality complete and tested
          - Windows native performance with Rust + Tauri
          - Lightweight (~20MB RAM usage)
          
          ### System Requirements
          - Windows 10 or later
          - .NET Framework 4.5+ (usually pre-installed)
          
          ### Coming Soon
          - macOS support
          - Linux support
          - Multi-language UI
          
          ### Support
          For issues or feature requests, please visit the [Issues page](https://github.com/frkavka/Atode-GUI/issues).
          
          ---
          **Note**: This release focuses on Windows to ensure the best user experience. Cross-platform support will be added in future releases.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
